"""add sender_id column

Revision ID: 53a4908a5954
Revises: a6459456f1a1
Create Date: 2026-07-24 10:11:05.425382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a4908a5954'
down_revision: Union[str, Sequence[str], None] = 'a6459456f1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'sender_id',
                sa.Integer(),
                sa.ForeignKey('users.id', name='fk_messages_sender_id_users'),
                nullable=False,
                server_default='0'
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
